services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\DomainModel\CheckoutSession\CheckoutSessionRepository: '@App\Infrastructure\Repository\CheckoutSessionPdoRepository'
