parameters:
  default_order_duration: 30

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $defaultOrderDuration: '%default_order_duration%'

  App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\DeleteAuthorization\DeleteAuthorizationController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\ConfirmAuthorization\ConfirmAuthorizationController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\UpdateConfirmedAuthorization\UpdateConfirmedAuthorizationController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\UpdateNotConfirmedAuthorization\UpdateNotConfirmedAuthorizationController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\Controllers\UpdateMerchantReferencesController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\ExtendAuthorizationExpiration\ExtendAuthorizationExpirationController:
    tags: [ 'controller.service_arguments' ]
