services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\UpdateConfirmedAuthorization\UpdateConfirmedAuthorizationController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\UpdateNotConfirmedAuthorization\UpdateNotConfirmedAuthorizationController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\Controllers\UpdateMerchantReferencesController:
    tags: [ 'controller.service_arguments' ]

