services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController:
    tags: [ 'controller.service_arguments' ]

  App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController:
    tags: [ 'controller.service_arguments' ]
