openapi: 3.0.0
info:
  title: 'Billie - PaD API Documentation'
  description: |
    # Introduction
    
    The PaD API provides an easy way to integrate both client and server-side 
    with our __Billie Pay After Delivery (PaD)__ platform.
    
    _Billie PaD_ is a Business to Business (B2B) platform that enables you (the merchant) to accept invoice payments from
    other business customers without having to wait for the money to arrive, caring about reminding customers to pay,
    or taking over any credit risk.
    
    Based upon your contractual agreement with Billie, your customers will have 14, 30, 45, 60, 90 or 120 days (payment terms) 
    to pay your invoices while Billie will transfer the money to you immediately after shipment of product or fulfilment of
    service obligation.
    
    If customers get late with paying their outstanding invoices, Billie will also take over reminding customers on your behalf 
    (white label solution). In case of your customer's bankruptcy, Billie fully covers this default for you.
    
    
  termsOfService: 'https://www.billie.io/agb/'
  license:
    name: '© Billie GmbH, 2019'
    url: 'https://www.billie.io/agb/'
  version: 2.4.0
  x-logo:
    url: 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIyLjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkViZW5lXzJfS29waWUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIKCSB5PSIwcHgiIHZpZXdCb3g9IjAgMCA0OC41IDY3LjYiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDQ4LjUgNjcuNjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtkaXNwbGF5Om5vbmU7ZmlsbDpub25lO3N0cm9rZTojMDAwMDAwO3N0cm9rZS13aWR0aDo3O3N0cm9rZS1taXRlcmxpbWl0OjEwO30KCS5zdDF7ZmlsbDojMUYyNTMwO30KCS5zdDJ7ZmlsbDpub25lO30KCS5zdDN7ZGlzcGxheTpub25lO2VuYWJsZS1iYWNrZ3JvdW5kOm5ldyAgICA7fQoJLnN0NHtmb250LWZhbWlseTonQXZlbmlyTmV4dC1EZW1pQm9sZCc7fQoJLnN0NXtmb250LXNpemU6My4wMzAzcHg7fQoJLnN0NntsZXR0ZXItc3BhY2luZzoyO30KPC9zdHlsZT4KPHBhdGggY2xhc3M9InN0MCIgZD0iTTkuOCw0Ni4xYy0wLjUsMCwyNS4xLTEyLjYsMjUuMS0zMi43YzAtNi45LTUuNi0xMi42LTEyLjYtMTIuNlM5LjcsNi41LDkuNywxMy40TDkuOCw0Ni4xaDE4LjUKCWM2LjksMCwxMi42LTUuNiwxMi42LTEyLjZTMzUuMiwyMSwyOC4yLDIxSDkuNyIvPgo8Zz4KCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0yOC4yLDQ3SDguOHYtMC44YzAtMC4xLDAtMC4yLDAtMC4zVjEzLjVDOC44LDYsMTQuOSwwLDIyLjMsMHMxMy41LDYsMTMuNSwxMy41YzAsMi44LTAuNSw1LjUtMS40LDguMgoJCWM0LjMsMi4yLDcuMyw2LjcsNy4zLDExLjlDNDEuNyw0MSwzNS42LDQ3LDI4LjIsNDd6IE0xMi45LDQ1LjJoMTUuM2M2LjQsMCwxMS43LTUuMywxMS43LTExLjdjMC00LjQtMi41LTguMy02LjEtMTAuMwoJCWMtMS44LDQuNC00LjgsOC43LTksMTIuOEMyMC40LDQwLjQsMTUuOCw0My41LDEyLjksNDUuMnogTTEwLjYsMjEuOXYyMi43YzEzLTcuNywxOC45LTE1LjYsMjEuNS0yMmMtMS4yLTAuNC0yLjUtMC43LTMuOS0wLjdIMTAuNgoJCXogTTEwLjYsMjAuMWgxNy42YzEuNiwwLDMuMSwwLjMsNC41LDAuOGMxLTIuOSwxLjMtNS41LDEuMy03LjRDMzQsNywyOC44LDEuOCwyMi4zLDEuOFMxMC42LDcsMTAuNiwxMy41VjIwLjF6Ii8+CjwvZz4KPHJlY3QgeD0iLTExLjEiIHk9Ii01OC43IiBjbGFzcz0ic3QyIiB3aWR0aD0iODUuNCIgaGVpZ2h0PSI0OS41Ii8+Cjx0ZXh0IHRyYW5zZm9ybT0ibWF0cml4KDEgMCAwIDEgLTEuMDQyNCA2Ny41NzcyKSIgY2xhc3M9InN0MyBzdDQgc3Q1IHN0NiI+QklMTElFPC90ZXh0Pgo8Zz4KCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0wLDU4LjFoMy43YzAuNCwwLDAuNywwLjEsMS4xLDAuMWMwLjQsMC4xLDAuNywwLjIsMC45LDAuNGMwLjMsMC4yLDAuNSwwLjQsMC43LDAuN2MwLjIsMC4zLDAuMywwLjcsMC4zLDEuMQoJCWMwLDAuNS0wLjIsMS0wLjUsMS4zYy0wLjMsMC40LTAuNywwLjYtMS4yLDAuOHYwYzAuNiwwLjEsMS4xLDAuMywxLjUsMC43QzYuOCw2My42LDcsNjQuMiw3LDY0LjhjMCwwLjUtMC4xLDEtMC4zLDEuMwoJCWMtMC4yLDAuNC0wLjUsMC42LTAuOCwwLjljLTAuMywwLjItMC43LDAuNC0xLjIsMC41Yy0wLjQsMC4xLTAuOSwwLjItMS4zLDAuMkgwQzAsNjcuNiwwLDU4LjEsMCw1OC4xeiBNMS43LDYyaDEuNQoJCWMwLjYsMCwxLTAuMSwxLjMtMC4zYzAuMy0wLjIsMC40LTAuNSwwLjQtMWMwLTAuNC0wLjItMC43LTAuNS0wLjljLTAuMy0wLjItMC44LTAuMy0xLjQtMC4zSDEuN0wxLjcsNjJMMS43LDYyeiBNMS43LDY2LjFoMS41CgkJYzAuMiwwLDAuNSwwLDAuNy0wLjFzMC41LTAuMSwwLjctMC4yYzAuMi0wLjEsMC40LTAuMywwLjUtMC40YzAuMS0wLjIsMC4yLTAuNCwwLjItMC44YzAtMC41LTAuMi0wLjktMC41LTEKCQljLTAuMy0wLjItMC45LTAuMy0xLjUtMC4zSDEuN1Y2Ni4xeiIvPgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTExLjEsNTguMWgxLjd2OS41aC0xLjdWNTguMXoiLz4KCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0xNy4zLDU4LjFoMS43djhoNHYxLjVoLTUuN1Y1OC4xeiIvPgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTI2LjUsNTguMWgxLjd2OGg0djEuNWgtNS43TDI2LjUsNTguMUwyNi41LDU4LjF6Ii8+Cgk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNMzUuNyw1OC4xaDEuN3Y5LjVoLTEuN1Y1OC4xeiIvPgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTQxLjksNTguMWg2LjN2MS41aC00LjZWNjJINDh2MS40aC00LjNWNjZoNC44djEuNWgtNi41VjU4LjF6Ii8+CjwvZz4KPC9zdmc+Cg=='
    href: '#'
servers:
  -
    url: 'http://paella-core.test{num}.ozean12.com'
    description: 'Test API (No Gateway)'
    variables:
      num:
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
          - '7'
          - '8'
          - '9'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
        default: '16'
        description: 'Test Server Instance'
  -
    url: 'https://private-api.paella.ozean12.com/test-{num}'
    description: 'Test Private API (AWS Gateway)'
    variables:
      instance:
        default: XXXXX
        description: 'AWS Gateway instance ID'
      num:
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
          - '7'
          - '8'
          - '9'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
        default: '16'
        description: 'Test Server Instance'
  -
    url: 'https://paella-private-api.billie.io/api'
    description: 'Production Private API (AWS Gateway)'
  -
    url: 'https://paella-sandbox.billie.io/api/v1'
    description: 'Test Sandbox API'
  -
    url: 'https://paella.billie.io/api/v1'
    description: 'Production API'
paths:
  /healthcheck:
    get:
      tags:
        - Misc.
      summary: 'API Status'
      description: 'Check the status of the API server.'
      operationId: api_status
      responses:
        '200':
          description: Successful
          content:
            text/plain:
              schema:
                type: string
                default: 'paella is alive'
  '/order/{uuid}/approve':
    post:
      tags:
        - 'Order Management'
      summary: 'Approve Order in Waiting State'
      description: 'Approves an order manually if it''s in waiting state. Otherwise this call fails.'
      operationId: order_approve
      parameters:
        -
          name: uuid
          in: path
          description: 'Order UUID'
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '204':
          description: 'Order approved.'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  '/order/{uuid}/decline':
    post:
      tags:
        - 'Order Management'
      summary: 'Decline Order in Waiting State'
      operationId: order_decline
      parameters:
        -
          name: uuid
          in: path
          description: 'Order UUID'
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '204':
          description: 'Order declined.'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  '/debtor-company/{uuid}/limits':
    get:
      tags:
        - Debtors
      summary: 'Get Debtor Company Limits'
      operationId: get_debtor_company_limits
      parameters:
        -
          name: uuid
          in: path
          description: 'Company UUID'
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDebtorCompanyLimitsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /merchant-debtor/mark-duplicates:
    post:
      tags:
        - Debtors
      summary: 'Mark Merchant Debtor Duplicates'
      operationId: mark_duplicate_debtors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                duplicates:
                  type: array
                  items: { $ref: '#/components/schemas/MarkDuplicateDebtorItem' }
                  nullable: false
              type: object
      responses:
        '204':
          description: 'Merchant debtor is marked as duplicate'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  '/order/{uuid}/mark-as-fraud':
    post:
      tags:
        - 'Order Management'
      summary: 'Mark Order As Fraud'
      operationId: mark_order_as_fraud
      parameters:
        -
          name: uuid
          in: path
          description: 'Order UUID'
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '204':
          description: 'Order Marked As Fraud'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  '/merchant-debtor/{debtorUuid}/update-limit':
    post:
      tags:
        - Debtors
      summary: 'Update Merchant Debtor Limit'
      operationId: update_merchant_debtor_limit
      parameters:
        -
          name: debtorUuid
          in: path
          description: 'Merchant Debtor UUID'
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                financing_limit:
                  description: 'New financing limit.'
                  type: number
                  format: float
              type: object
      responses:
        '204':
          description: 'Successful response'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  '/merchant-debtor/{debtorUuid}/whitelist':
    post:
      tags:
        - Debtors
      summary: 'Whitelist Merchant Debtor'
      operationId: whitelist_merchant_debtor
      parameters:
        -
          name: debtorUuid
          in: path
          description: 'Merchant-Debtor UUID'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                is_whitelisted:
                  type: boolean
                  nullable: false
              type: object
      responses:
        '204':
          description: 'Merchant debtor is whitelisted'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    UUID:
      type: string
      format: uuid
      maxLength: 36
      minLength: 36
      example: 12345667-890a-bcde-f123-34567890abcd
    Money:
      title: Money
      type: number
      format: float
      pattern: '^(\d{1,}(.\d{2})?)$'
      example: 7500
    GetDebtorCompanyLimitsMerchant:
      title: 'Debtor''s Merchant IDs Object'
      properties:
        id:
          type: integer
        payment_uuid:
          $ref: '#/components/schemas/UUID'
      type: object
    GetDebtorCompanyLimitsResponse:
      title: 'Debtor Company Limits Object'
      properties:
        company_id:
          type: integer
        company_uuid:
          $ref: '#/components/schemas/UUID'
        company_financing_power:
          description: 'Current available limit for this company in Platform.'
          example: 10000
          allOf:
            -
              $ref: '#/components/schemas/Money'
        merchant_debtors:
          description: 'List of debtors created in Paella for this company.'
          type: array
          items:
            properties:
              id:
                description: 'Merchant Debtor ID'
                type: integer
              uuid:
                description: 'Merchant Debtor UUID'
                $ref: '#/components/schemas/UUID'
              financing_limit:
                description: 'Full limit assigned in Paella to this debtor and merchant combination.'
                example: 2500
                allOf:
                  - { $ref: '#/components/schemas/Money' }
              financing_power:
                description: 'Current available limit in Paella for this debtor and merchant combination.'
                example: 2251.01
                allOf:
                  - { $ref: '#/components/schemas/Money' }
              merchant:
                description: 'The merchant the merchant-debtor belongs to.'
                $ref: '#/components/schemas/GetDebtorCompanyLimitsMerchant'
            type: object
      type: object
    MarkDuplicateDebtorItem:
      required:
        - debtor_id
        - is_duplicate_of
      properties:
        debtor_id:
          type: integer
        is_duplicate_of:
          type: integer
      type: object
    ErrorsObject:
      title: 'API Errors'
      properties:
        errors:
          type: array
          items:
            required:
              - title
              - code
            properties:
              title:
                description: 'Error message'
                type: string
              code:
                description: 'Error code'
                type: string
                nullable: true
              source:
                description: 'Property path where the error occurred, if applicable'
                type: string
                nullable: true
            type: object
      type: object
  responses:
    ServerError:
      description: 'Unexpected Server Error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsObject'
    NotFound:
      description: 'Resource Not Found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsObject'
    Unauthorized:
      description: 'Unauthorized request or invalid credentials'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsObject'
    Forbidden:
      description: 'Forbidden Request. The operation cannot be completed.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsObject'
    BadRequest:
      description: 'Invalid Request Data'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsObject'
  securitySchemes:
    oauth2:
      type: oauth2
      description: |
        This authentication mechanism is based on the OAuth 2.0 prototocol and requires a Client ID, a Client Secret Key and
        in some cases also a user and password.
        
        With these credentials, the client should request a token using the `POST /api/v1/oauth/token` endpoint,
        which should be used in the `Authorization` header together with the `Bearer` challenge to authenticate all the requests.
        
        > Example: `Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`.
      flows:
        password:
          tokenUrl: /oauth/token
          scopes:
            default: default
tags:
  -
    name: 'Order Management'
  -
    name: Debtors
  -
    name: Misc.
