billie_pdo:
  connections:
    default:
      dsn: 'mysql:dbname=%env(DATABASE_NAME)%;host=%env(DATABASE_HOST)%;charset=UTF8'
      username: '%env(DATABASE_USERNAME)%'
      password: '%env(DATABASE_PASSWORD)%'
      retries: 3
      retry_delay: 100

ozean12_graphql_client:
  dsn: '%env(GRAPHQL_ENDPOINT)%'
  api_key: "%env(GRAPHQL_API_KEY)%"

ozean12_amqp_pack:
  publish:
    customer.customer_created: Ozean12\Transfer\Message\Customer\CustomerCreated
    bank_account.bank_account_core_accepted: Ozean12\Transfer\Message\BankAccount\BankAccountCoreAccepted
    company_information_change_request.company_information_change_request_canceled: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestCanceled
    company_information_change_request.company_information_change_request_created: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestCreated
    company.request_schufa_b2b_report: Ozean12\Transfer\Message\Company\RequestSchufaB2BReport
    merchant_onboarding.merchant_onboarding_step_transition: Ozean12\Transfer\Message\MerchantOnboarding\MerchantOnboardingStepTransition
    merchant_user.merchant_user_new_password_requested: Ozean12\Transfer\Message\MerchantUser\MerchantUserNewPasswordRequested
    customer.customer_fee_rates_updated:
      class: Ozean12\Transfer\Message\Customer\CustomerFeeRatesUpdated
      delay: 15000
    invoice.create_invoice: Ozean12\Transfer\Message\Invoice\CreateInvoice
    invoice.extend_invoice: Ozean12\Transfer\Message\Invoice\ExtendInvoice
    document.document_uploaded:
      class: Ozean12\Transfer\Message\Document\DocumentUploaded
      delay: 5000
    merchant_user_invitation.merchant_user_invitation_created: Ozean12\Transfer\Message\MerchantUserInvitation\MerchantUserInvitationCreated
  subscribe:
    identity.identity_verification_succeeded: Ozean12\Transfer\Message\Identity\IdentityVerificationSucceeded
    order.order_dunning_step_changed: Ozean12\Transfer\Message\Order\OrderDunningStepChanged
    company_information_change_request.company_information_change_request_decision_issued: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestDecisionIssued
    customer.customer_created: Ozean12\Transfer\Message\Customer\CustomerCreated

billie_monitoring:
  strict_logging: true
