billie_pdo:
  connections:
    default:
      dsn: 'mysql:dbname=%env(DATABASE_NAME)%;host=%env(DATABASE_HOST)%;charset=UTF8'
      username: '%env(DATABASE_USERNAME)%'
      password: '%env(DATABASE_PASSWORD)%'
      retries: 3
      retry_delay: 100

ozean12_graphql_client:
  dsn: '%env(GRAPHQL_ENDPOINT)%'
  api_key: "%env(GRAPHQL_API_KEY)%"

ozean12_amqp_pack:
  publish:
    customer.customer_created: Ozean12\Transfer\Message\Customer\CustomerCreated
    bank_account.bank_account_core_accepted: Ozean12\Transfer\Message\BankAccount\BankAccountCoreAccepted
    company_information_change_request.company_information_change_request_canceled: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestCanceled
    company_information_change_request.company_information_change_request_created: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestCreated
    company.request_schufa_b2b_report: Ozean12\Transfer\Message\Company\RequestSchufaB2BReport
