parameters:
  blacklisted_addresses:
    -
      street: 'Zugstr.'
      house: '28'
      postal_code: '45357'
      city: 'Essen'
    -
      street: 'Kohlbrandstr.'
      house: '24'
      postal_code: '60385'
      city: 'Frankfurt am Main'
    -
      street: 'Paapsandstr.'
      house: '15'
      postal_code: '26723'
      city: 'Emden'
    -
      street: 'Waldstr.'
      house: '31'
      postal_code: '64625'
      city: 'Bensheim'
    -
      street: 'Bornholmerstr.'
      house: '84'
      postal_code: '10439'
      city: 'berlin'
