eight_points_guzzle:
  clients:
    alfred:
      base_url: "%env(string:ALFRED_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    borscht:
      base_url: "%env(string:BORSCHT_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    smaug:
      base_url: "%env(string:SMAUG_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    nachos:
      base_url: "%env(string:NACHOS_URL)%"
    webhook:
    invoice_download:
