eight_points_guzzle:
  clients:
    risky:
      base_url: "%env(RISKY_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    alfred:
      base_url: "%env(ALFRED_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    borscht:
      base_url: "%env(BORSCHT_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    webhook:

