eight_points_guzzle:
  clients:
    webhook:
      options:
        timeout: 2
    url_downloader:
    alfred:
      base_url: "%env(string:ALFRED_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
    borscht:
      base_url: "%env(string:BORSCHT_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
      plugin:
        retry:
          retry_enabled: true
          max_retry_attempts: 3
          retry_on_status: [ 404 ]
          default_retry_multiplier: 0.25 #250ms, 500ms, 750ms
    smaug:
      base_url: "%env(string:SMAUG_URL)%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
    nachos:
      base_url: "%env(string:NACHOS_URL)%"
    limes:
      base_url: "%env(string:LIMES_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    salesforce:
      base_url: "%env(string:SALESFORCE_API_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
          X-Api-Key: "%env(string:SALESFORCE_API_KEY)%"
    paella_sandbox:
      base_url: "%env(string:PAELLA_SANDBOX_URL)%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
          X-Api-Key: "%env(string:PAELLA_SANDBOX_API_KEY)%"
    paella_prod:
      base_url: "%env(string:PAELLA_PROD_URL)%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
          X-Api-Key: "%env(string:PAELLA_PROD_API_KEY)%"
    webapp:
      base_url: "%env(string:WEBAPP_URL)%"
      options:
        timeout: 5
        headers:
          Content-Type: "application/json"
          X-Api-Key: "%env(string:WEBAPP_API_KEY)%"
    fintech_toolbox:
      base_url: "%env(string:FINTECH_TOOLBOX_API_URL)%"
      options:
        timeout: 5
        headers:
          Authorization: "token %env(string:FINTECH_TOOLBOX_API_KEY)%"
    document_generator:
      base_url: "%env(string:DOCUMENT_GENERATOR_URL)%"
      options:
        timeout: 5
        headers:
          Content-Type: "application/json"
    jarvis:
      base_url: "%env(string:JARVIS_URL)%"
      options:
        headers:
          Content-Type: "application/json"
    watson:
      base_url: "%env(string:WATSON_URL)%"
      options:
        timeout: 5
        headers:
          Content-Type: "application/json"
    invoice_butler:
      base_url: "%env(string:INVOICE_BUTLER_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
    cosimi:
      base_url: "%env(string:COMPANIES_SIMILARITY_URL)%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
    volt:
      base_url: "%env(string:VOLT_API_URL)%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
    sepa:
      base_url: "%env(string:SEPA_URL)%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
    banco:
      base_url: "%banco_url%"
      options:
        timeout: 2
        headers:
          Content-Type: "application/json"
