eight_points_guzzle:
  clients:
    alfred:
      base_url: "%env(string:ALFRED_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
    borscht:
      base_url: "%env(string:BORSCHT_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
    smaug:
      base_url: "%env(string:SMAUG_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
    nachos:
      base_url: "%env(string:NACHOS_URL)%"
    salesforce:
      base_url: "%env(string:SALESFORCE_API_URL)%"
      options:
        timeout: 1
        headers:
          Content-Type: "application/json"
          X-Api-Key: "%env(string:SALESFORCE_API_KEY)%"
    webhook:
    invoice_download:
