# See full configuration at https://github.com/bestit/flagception-bundle
flagception:
    features:
        dummy_risk_checks:
            default: false
        invoice_butler_enabled:
            env: INVOICE_BUTLER_ENABLED
