framework:
    messenger:
      default_bus: default
        # For some reason the compiler pass won't trigger prepend. So the hack it is for now.
      buses:
        default:
          middleware:
            - 'Ozean12\AmqpPackBundle\Middleware\TransportConfigurationMiddleware'
      transports:
        customer.customer_fee_rates_updated: enqueue://default?topic[name]=customer&topic[type]=topic&queue[name]=customer.customer_fee_rates_updated&deliveryDelay=30000&delayStrategy=Enqueue\AmqpTools\RabbitMqDlxDelayStrategy&timeToLive=30000&receiveTimeout=1000&queue[bindingKey]=customer.customer_fee_rates_updated

      routing:
        Ozean12\Transfer\Message\Customer\CustomerFeeRatesUpdated: customer.customer_fee_rates_updated

