ozean12_amqp_pack:
  publish:
    customer.customer_created: Ozean12\Transfer\Message\Customer\CustomerCreated
    bank_account.bank_account_core_accepted: Ozean12\Transfer\Message\BankAccount\BankAccountCoreAccepted
    company_information_change_request.company_information_change_request_canceled: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestCanceled
    company_information_change_request.company_information_change_request_created: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestCreated
    company.request_schufa_b2b_report: Ozean12\Transfer\Message\Company\RequestSchufaB2BReport
    merchant_onboarding.merchant_onboarding_step_transition: Ozean12\Transfer\Message\MerchantOnboarding\MerchantOnboardingStepTransition
    merchant_user.merchant_user_new_password_requested: Ozean12\Transfer\Message\MerchantUser\MerchantUserNewPasswordRequested
    customer.customer_fee_rates_updated:
      class: Ozean12\Transfer\Message\Customer\CustomerFeeRatesUpdated
      delay: 15000
    invoice.create_invoice: Ozean12\Transfer\Message\Invoice\CreateInvoice
    invoice.extend_invoice: Ozean12\Transfer\Message\Invoice\ExtendInvoice
    credit_note.create_credit_note:
      class: Ozean12\Transfer\Message\CreditNote\CreateCreditNote
      delay: 5000
    document.document_uploaded:
      class: Ozean12\Transfer\Message\Document\DocumentUploaded
      delay: 5000
    merchant_user_invitation.merchant_user_invitation_created: Ozean12\Transfer\Message\MerchantUserInvitation\MerchantUserInvitationCreated
    merchant_user_invitation.merchant_user_registered: Ozean12\Transfer\Message\MerchantUserInvitation\MerchantUserRegistered
    order.order_created: Ozean12\Transfer\Message\Order\OrderCreated
  subscribe:
    identity.identity_verification_succeeded: Ozean12\Transfer\Message\Identity\IdentityVerificationSucceeded
    order.order_dunning_step_changed: Ozean12\Transfer\Message\Order\OrderDunningStepChanged
    company_information_change_request.company_information_change_request_decision_issued: Ozean12\Transfer\Message\CompanyInformationChangeRequest\CompanyInformationChangeRequestDecisionIssued
    customer.customer_created: Ozean12\Transfer\Message\Customer\CustomerCreated
    invoice.invoice_financing_workflow_paid_out: Ozean12\Transfer\Message\Invoice\InvoiceFinancingWorkflowPaidOut
    invoice.invoice_marked_as_late: Ozean12\Transfer\Message\Invoice\InvoiceMarkedAsLate
    invoice.invoice_completed: Ozean12\Transfer\Message\Invoice\InvoiceCompleted
    ticket.ticket_outstanding_amount_changed: Ozean12\Transfer\Message\Ticket\TicketOutstandingAmountChanged
  local:
    order_debtor_identification_v2: App\DomainModel\Order\DomainEvent\OrderDebtorIdentificationV2DomainEvent
    http_upload_invoice: App\DomainModel\OrderInvoiceDocument\DomainEvent\HttpUploadInvoiceDomainEvent
    notification_delivery:
      class: App\DomainModel\Order\DomainEvent\NotificationDeliveryDomainEvent
      delay: 1000
    order_in_waiting_state:
      class: App\DomainModel\Order\DomainEvent\OrderInWaitingStateDomainEvent
      delay: 1000
    order_in_pre_waiting_state:
      class: App\DomainModel\Order\DomainEvent\OrderInPreWaitingStateDomainEvent
      delay: 1000
    order_in_authorized_state:
      class: App\DomainModel\Order\DomainEvent\OrderInAuthorizedStateDomainEvent
      delay: 1000
