security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        healthcheck:
            pattern: ^/healthcheck
            security: false

        private_api:
            pattern: ^/private/*
            security: false

        api_docs:
            pattern: ^/(docs|internal-docs)(/.*)?
            security: false

        merchant_user_login:
            pattern: ^/(public/)?merchant/user/login
            security: false

        merchant_user_logout:
            pattern: ^/(public/)?merchant/user/logout
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator

        legal_forms:
            pattern: ^/(public/)?legal-forms
            security: false

        checkout_authorize:
            pattern: ^/(public/)?checkout-session/.*/authorize
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\CheckoutSessionAuthenticator

        default_security:
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator
                    - App\Http\Authentication\Authenticator\ApiKeyAuthenticator
                entry_point: App\Http\Authentication\Authenticator\OAuthTokenAuthenticator

    access_control: # TODO: secure all other endpoints properly (the ones under default_security)
        - path: "^/(public/)?checkout-session/.*/authorize"
          roles: [ ROLE_AUTHENTICATED_AS_CHECKOUT_USER ]
          methods: PUT
        - path: "^/(public/)?orders"
          roles: [ ROLE_VIEW_ORDERS ]
          methods: GET
        - path: "^/(public/)?debtors"
          roles: [ ROLE_VIEW_DEBTORS ]
          methods: GET
        - path: "^/(public/)?payments"
          roles: [ ROLE_VIEW_PAYMENTS ]
          methods: GET
        - path: "^/(public/)?order/.*/confirm-payment"
          roles: [ ROLE_AUTHENTICATED_AS_MERCHANT, ROLE_CONFIRM_ORDER_PAYMENT ]
          methods: POST
        - path: "^/(public/)?order/.*/pause-dunning"
          roles: [ ROLE_PAUSE_DUNNING ]
          methods: POST
