security:
  providers:
    in_memory: { memory: ~ }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    healthcheck:
      pattern: ^/(public/)?healthcheck
      security: false

    private_api:
      pattern: ^/private/*
      security: false # handled via AWS

    api_docs:
      pattern: ^/(docs|internal-docs)(/.*)?
      security: false

    legal_forms:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?legal-forms
      security: false

    # ---------------------------------------- #
    # DASHBOARD
    # ---------------------------------------- #

    merchant_user_login:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/user/login
      security: false

    merchant_user_logout:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/user/logout
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator

    merchant_user_request_new_password:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/user/request-new-password
      security: false

    merchant_user_confirm_password_reset:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/user/confirm-password-reset
      security: false

    merchant_user_reset_password:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/user/reset-password
      security: false

    merchant_user_invitations:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/users/invitations/([a-z0-9])+/(signup|details)$
      methods: [ GET, POST, OPTIONS ]
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\InvitedUserTokenAuthenticator

    merchant_signatory_powers:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?merchant/signatory-powers/.*(/(start-identity-verification))?
      methods: [ GET, POST, OPTIONS ]
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\SignatoryPowerTokenAuthenticator

    # ---------------------------------------- #
    # CHECKOUT
    # ---------------------------------------- #

    checkout_authorize:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?checkout-session/.*/authorize
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\ActiveCheckoutSessionAuthenticator

    checkout_update:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?checkout-session/.*/update
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\ExistingCheckoutSessionAuthenticator

    checkout_sign_mandate:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?checkout-session/.*/sign-mandate
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\ExistingCheckoutSessionAuthenticator

    checkout_decline:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?checkout-session/.*/decline
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\ExistingCheckoutSessionAuthenticator

    get_external_debtors:
      pattern: ^/(public/)?(api/)?(v[1-2]/)?external-debtors
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\ActiveCheckoutSessionAuthenticator
          - App\Http\Authentication\Authenticator\SandboxAuthenticator
        entry_point: App\Http\Authentication\Authenticator\ActiveCheckoutSessionAuthenticator

    # ---------------------------------------- #
    # DEFAULTS
    # ---------------------------------------- #

    sandbox_security:
      anonymous: false
      stateless: true
      request_matcher: sandbox_request_matcher
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\SandboxAuthenticator
          - App\Http\Authentication\Authenticator\ApiKeyAuthenticator
        entry_point: App\Http\Authentication\Authenticator\SandboxAuthenticator

    default_security:
      anonymous: false
      stateless: true
      guard:
        authenticators:
          - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator
          - App\Http\Authentication\Authenticator\ApiKeyAuthenticator
        entry_point: App\Http\Authentication\Authenticator\OAuthTokenAuthenticator
