security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        healthcheck:
            pattern: ^/healthcheck
            security: false
        support_api: # TODO: move all support endpoints under the /support/ API prefix
            pattern: ^/(merchant|merchant-debtor)/
            security: false
        checkout_authorize:
            pattern: ^/checkout-session/.*/authorize
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\CheckoutSessionAuthenticator
        api_default:
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\ApiKeyAuthenticator
                    - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator
                entry_point: App\Http\Authentication\Authenticator\ApiKeyAuthenticator

    access_control:
         - { path: ^/, roles: [ROLE_USER, ROLE_MERCHANT] }
         - { path: ^/checkout-session/.*/authorize, roles: [ROLE_CHECKOUT_USER] }
