security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        healthcheck:
            pattern: ^/healthcheck
            security: false

        merchant_user_login:
            pattern: ^/(public/)?merchant/user/login
            security: false

        merchant_user_logout:
            pattern: ^/(public/)?merchant/user/logout
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator

        checkout_authorize:
            pattern: ^/(public/)?checkout-session/.*/authorize
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\CheckoutSessionAuthenticator

        support_api: # TODO: move all support endpoints under the /private/ API prefix
            pattern: ^/(merchant|merchant-debtor)/*
            security: false

        docs:
            pattern: ^/(private/|public/)?(docs|internal-docs)(/.*)?
            security: false

        default_security:
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Http\Authentication\Authenticator\OAuthTokenAuthenticator
                    - App\Http\Authentication\Authenticator\ApiKeyAuthenticator
                entry_point: App\Http\Authentication\Authenticator\OAuthTokenAuthenticator

    access_control:
         - { path: ^/, roles: [ROLE_USER, ROLE_MERCHANT] }
         - { path: ^/checkout-session/.*/authorize, roles: [ROLE_CHECKOUT_USER] }
