framework:
  workflows:
    order:
      type: state_machine
      marking_store:
        type: single_state
        arguments:
          - state
      supports: App\DomainModel\Order\OrderEntity
      places:
        - new
        - waiting
        - created
        - declined
        - shipped
        - paid_out
        - late
        - complete
        - canceled
        - authorized
        - pre_approved
      transitions:
        waiting:
          from: new
          to: waiting
        create:
          from: [new, waiting, authorized, pre_approved]
          to: created
        decline:
          from: [new, waiting, pre_approved]
          to: declined
        ship:
          from: created
          to: shipped
        pay_out:
          from: shipped
          to: paid_out
        late:
          from: [shipped, paid_out]
          to: late
        complete:
          from: [shipped, paid_out, late]
          to: complete
        cancel:
          from: [new, created, waiting]
          to: canceled
        cancel_shipped:
          from: [shipped, paid_out, late]
          to: canceled
        authorize:
          from: new
          to: authorized
        pre_approve:
          from: new
          to: pre_approved

    merchant_onboarding:
      type: state_machine
      marking_store:
        type: single_state
        arguments:
          - state
      supports: App\DomainModel\MerchantOnboarding\MerchantOnboardingEntity
      places:
        - new
        - complete
        - canceled
      transitions:
        complete:
          from: new
          to: complete
        cancel:
          from: new
          to: canceled

    merchant_onboarding_step:
      type: state_machine
      marking_store:
        type: single_state
        arguments:
          - state
      supports: App\DomainModel\MerchantOnboarding\MerchantOnboardingStepEntity
      places:
        - new
        - confirmation_pending
        - complete
      transitions:
        request_confirmation:
          from: [new, complete]
          to: confirmation_pending
        complete:
          from: [new, confirmation_pending]
          to: complete
        new:
          from: [complete, confirmation_pending]
          to: new
