framework:
  workflows:
    order:
      type: state_machine
      marking_store:
        type: single_state
        arguments:
          - state
      supports: App\DomainModel\Order\OrderEntity
      places:
        - new
        - waiting
        - created
        - declined
        - shipped
        - paid_out
        - late
        - complete
        - canceled
        - authorized
        - pre_approved
      transitions:
        waiting:
          from: new
          to: waiting
        create:
          from: [new, waiting, authorized, pre_approved]
          to: created
        decline:
          from: [new, waiting, pre_approved]
          to: declined
        ship:
          from: created
          to: shipped
        pay_out:
          from: shipped
          to: paid_out
        late:
          from: [shipped, paid_out]
          to: late
        complete:
          from: [shipped, paid_out, late]
          to: complete
        cancel:
          from: [new, created]
          to: canceled
        cancel_shipped:
          from: [shipped, paid_out, late]
          to: canceled
        authorize:
          from: new
          to: authorized
        pre_approve:
          from: new
          to: pre_approved
