framework:
  workflows:
    order:
      type: state_machine
      marking_store:
        type: method
        property: state
      supports: App\DomainModel\Order\OrderEntity
      places:
        - new
        - waiting
        - created
        - declined
        - shipped
        - paid_out
        - late
        - complete
        - canceled
        - pre_waiting
        - authorized
      transitions:
        pre_waiting:
          from: new
          to: pre_waiting
        waiting:
          from: [new, pre_waiting]
          to: waiting
        create:
          from: [new, waiting, authorized]
          to: created
        decline:
          from: [new, waiting, authorized, pre_waiting]
          to: declined
        ship:
          from: created
          to: shipped
        pay_out:
          from: shipped
          to: paid_out
        late:
          from: [shipped, paid_out]
          to: late
        complete:
          from: [shipped, paid_out, late]
          to: complete
        cancel:
          from: [new, created]
          to: canceled
        cancel_waiting:
          from: [waiting]
          to: canceled
        cancel_shipped:
          from: [shipped, paid_out, late]
          to: canceled
        authorize:
          from: [new]
          to: authorized

    merchant_onboarding:
      type: state_machine
      marking_store:
        type: method
        property: state
      supports: App\DomainModel\MerchantOnboarding\MerchantOnboardingEntity
      places:
        - new
        - complete
        - canceled
      transitions:
        complete:
          from: new
          to: complete
        cancel:
          from: new
          to: canceled

    merchant_onboarding_step:
      type: state_machine
      marking_store:
        type: method
        property: state
      supports: App\DomainModel\MerchantOnboarding\MerchantOnboardingStepEntity
      places:
        - new
        - confirmation_pending
        - complete
      transitions:
        request_confirmation:
          from: [new, complete]
          to: confirmation_pending
        complete:
          from: [new, confirmation_pending]
          to: complete
        new:
          from: [complete, confirmation_pending]
          to: new

    debtor_information_change_request:
      type: state_machine
      marking_store:
        type: method
        property: state
      supports: App\DomainModel\DebtorInformationChangeRequest\DebtorInformationChangeRequestEntity
      places:
        - new
        - confirmation_pending
        - complete
        - declined
        - canceled
      transitions:
        request_confirmation:
          from: [new]
          to: confirmation_pending
        complete_manually:
          from: [confirmation_pending]
          to: complete
        complete_automatically:
          from: [new]
          to: complete
        decline_manually:
          from: [confirmation_pending]
          to: declined
        cancel:
          from: [confirmation_pending]
          to: canceled
