#
# If needed, copy this file and rename it to docker-compose.override.yml
# Anything you add in that override file will be merged automatically by docker-compose with the main YAML file.
#
# This way you can have your own custom docker-compose config, add new services, change config, etc.
#
# Run "docker-compose config" to see the merged version and validate it.
#
---
version: "2.4"
services:
  app:
    entrypoint: []
    environment:
      - APP_DEBUG=1
      - PHP_XDEBUG_ENABLED=true
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_PROCESS_TIMEOUT=0
      - COMPOSER_MEMORY_LIMIT=3G # Needed to not run out of memory when installing all SF packages for first time
    volumes:
      - './:/var/www/paella-core'
      - '~/.composer:/composer'  # required to install private packages and use your auth.json in the container

  mysql:
    ports:
      - "3308:3306" # This allows you to connect to this MySQL container, if needed
