---
version: "2.4"
services:
  app: # Do not rename this service: it is required by provisioner/jenkins.
    build:
      context: .
      target: builder
    entrypoint: "/usr/local/bin/docker-php-entrypoint"
    command: "sleep 1h" # keep-alive, specially for the CI
    volumes:
      - './:/var/www/paella-core'
    depends_on:
      - mysql
    environment:
      - PHP_MEMORY_LIMIT=256M
      - APP_ENV=test
      - APP_NAME=paella-core
      - APP_SECRET=abcdef0123456789abcdef0123456789
      - INSTANCE_SUFFIX=_test
      - SENTRY_DSN=
      - NEWRELIC_APP_KEY=
      - COMPOSER_NO_INTERACTION=1
      - COMPOSER_MEMORY_LIMIT=0
      - DATABASE_DRIVER=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=paella
      - DATABASE_USERNAME=paella
      - DATABASE_PASSWORD=test
      - ENQUEUE_DSN=null://
      - ALFRED_URL=
      - AWS_ACCESS_KEY_ID=TEST
      - AWS_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=test
      - BORSCHT_URL=
      - GRAPHQL_API_KEY=test
      - GRAPHQL_ENDPOINT=http://localhost:7070
      - LIMES_URL=
      - MOCKSERVER_URL=
      - NACHOS_URL=
      - RABBITMQ_HOST=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - RECEIVE_INVOICES_SNS_TOPIC_ARN=
      - RISKY_URL=
      - SALESFORCE_API_KEY=
      - SALESFORCE_API_URL=
      - SLACK_WEBHOOK_URL=
      - SMAUG_CLIENT_ID=
      - SMAUG_CLIENT_SECRET=
      - SMAUG_URL=
      - FINTECH_TOOLBOX_API_URL=
      - FINTECH_TOOLBOX_API_KEY=
      - DOCUMENT_GENERATOR_URL=

  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=16M --query_cache_size=8M --query_cache_limit=512K --thread_stack=128K --max_connections=50 --thread_cache_size=4 --interactive_timeout=20 --wait_timeout=10 --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql-mode=NO_ENGINE_SUBSTITUTION
    environment:
      - MYSQL_DATABASE=paella
      - MYSQL_USER=paella
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    healthcheck:
      test: CMD mysqladmin -ptest ping -h localhost
      interval: 5s
      timeout: 20s
      retries: 20

  swagger-cli:
    build:
      context: .ci/docker/swagger-cli
    volumes:
      - './docs/openapi/:/openapi'
