initiate:
  path: /initiate
  controller: App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController::execute
  methods: POST

authorize:
  path: /authorizations
  controller: App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController::execute
  methods: POST

delete_authorization:
  path: /authorizations/{orderId}/delete
  controller: App\UserInterface\Http\KlarnaScheme\DeleteAuthorization\DeleteAuthorizationController::execute
  methods: POST

confirm_authorization:
  path: /authorizations/{orderId}/confirm
  controller: App\UserInterface\Http\KlarnaScheme\ConfirmAuthorization\ConfirmAuthorizationController::execute
  methods: POST

update_confirmed_authorization:
  path: /authorizations/{orderId}/adjust-order
  controller: App\UserInterface\Http\KlarnaScheme\UpdateConfirmedAuthorization\UpdateConfirmedAuthorizationController::execute
  methods: POST

updated_not_confirm_adjust:
  path: /authorizations/{orderId}
  controller: App\UserInterface\Http\KlarnaScheme\UpdateNotConfirmedAuthorization\UpdateNotConfirmedAuthorizationController::execute
  methods: POST

update_customer_details:
  path: /authorizations/{orderId}/customer-details
  controller: App\UserInterface\Http\KlarnaScheme\UpdateCustomerDetails\UpdateCustomerDetailsController::execute
  methods: POST

update_merchant_references:
  path: /authorizations/{orderId}/merchant-references
  controller: App\UserInterface\Http\KlarnaScheme\UpdateMerchantReferences\UpdateMerchantReferencesController::execute
  methods: POST

extend_authorization_expiration:
  path: /authorizations/{orderId}/extend-expiration
  controller: App\UserInterface\Http\KlarnaScheme\ExtendAuthorizationExpiration\ExtendAuthorizationExpirationController::execute
  methods: POST

cancel_authorization:
  path: /authorizations/{orderId}/cancel
  controller: App\UserInterface\Http\KlarnaScheme\CancelAuthorization\CancelAuthorizationController::execute
  methods: POST
