initiate:
  path: /initiate
  controller: App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController::execute
  methods: POST

authorize:
  path: /authorizations
  controller: App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController::execute
  methods: POST

updated_not_confirm_adjust:
  path: /authorizations/{orderId}
  controller: App\UserInterface\Http\KlarnaScheme\UpdateNotConfirmedAuthorization\UpdateNotConfirmedAuthorizationController::execute
  methods: POST
