initiate:
  path: /initiate
  controller: App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController::execute
  methods: POST

authorize:
  path: /authorizations
  controller: App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController::execute
  methods: POST

update_confirmed_authorization:
  path: /authorizations/{orderId}/adjust-order
  controller: App\UserInterface\Http\KlarnaScheme\UpdateConfirmedAuthorization\UpdateConfirmedAuthorizationController::execute

updated_not_confirm_adjust:
  path: /authorizations/{orderId}
  controller: App\UserInterface\Http\KlarnaScheme\UpdateNotConfirmedAuthorization\UpdateNotConfirmedAuthorizationController::execute
  methods: POST

update_merchant_references:
  path: /authorizations/{orderId}/merchant-references
  controller: App\UserInterface\Http\KlarnaScheme\Controllers\UpdateMerchantReferencesController::execute
  methods: POST

extend_authorization_expiration:
  path: /authorizations/{orderId}/extend-expiration
  controller: App\UserInterface\Http\KlarnaScheme\ExtendAuthorizationExpiration\ExtendAuthorizationExpirationController::execute
  methods: POST
