initiate:
  path: /initiate
  controller: App\UserInterface\Http\KlarnaScheme\Initiate\InitiateController::execute
  methods: POST

authorize:
  path: /authorizations
  controller: App\UserInterface\Http\KlarnaScheme\Authorize\AuthorizeController::execute
  methods: POST
