eight_points_guzzle:
  clients:
    alfred:
      options:
        timeout: 5
    borscht:
      options:
        timeout: 5
    smaug:
      options:
        timeout: 5
    webapp:
      options:
        timeout: 15
