monolog:
  handlers:
    main:
      type: "stream"
      path: "php://stdout"
      level: info
      channels: ["!event", "!translation", "!request"]
      formatter: Monolog\Formatter\JsonFormatter
