name: PHP Jobs

on: [ push, pull_request ]

jobs:
  build:
    name: PHP ${{ matrix.php-version }} Test
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        php-version: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP Version ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Check PHP formating style
        run: composer run-script php-cs-fixer-check

      - name: Static code analysis
        run: composer run-script phpstan




