get_order:
  path: /order/{externalCode}
  controller: App\Http\Controller\GetOrderController::execute
  methods: [GET]

create_order:
  path: /order
  controller: App\Http\Controller\CreateOrderController::execute
  methods: [POST]

get_merchant:
  path: /merchant/{apiKey}
  controller: App\Http\Controller\GetMerchantController::execute
  methods: [GET]

cancel_order:
  path: /order/{externalCode}/cancel
  controller: App\Http\Controller\CancelOrderController::execute
  methods: [POST]

update_order:
  path: /order/{externalCode}
  controller: App\Http\Controller\UpdateOrderController::execute
  methods: [PATCH]

confirm_order_payment:
  path: /order/{externalCode}/confirm-payment
  controller: App\Http\Controller\ConfirmOrderPaymentController::execute
  methods: [POST]

ship_order:
  path: /order/{externalCode}/ship
  controller: App\Http\Controller\ShipOrderController::execute
  methods: [POST]

health_check:
  path: /healthcheck
  controller:  App\Infrastructure\Monitoring\Controller\HealthCheckController::execute
  methods: [GET]
