health_check:
  path: /health-check
  controller: App\Http\Controller\HealthCheckController::execute
  methods: [GET]

get_order:
  path: /order/{externalCode}
  controller: App\Http\Controller\GetOrderController::execute
  methods: [GET]
