billie_monitoring:
  resource: '@BillieMonitoringBundle/Resources/config/routes.yaml'

get_order:
  path: /order/{externalCode}
  controller: App\Http\Controller\GetOrderController::execute
  methods: [GET]

create_order:
  path: /order
  controller: App\Http\Controller\CreateOrderController::execute
  methods: [POST]

get_merchant:
  path: /merchant/{apiKey}
  controller: App\Http\Controller\GetMerchantController::execute
  methods: [GET]

cancel_order:
  path: /order/{externalCode}/cancel
  controller: App\Http\Controller\CancelOrderController::execute
  methods: [POST]

update_order:
  path: /order/{externalCode}
  controller: App\Http\Controller\UpdateOrderController::execute
  methods: [PATCH]

confirm_order_payment:
  path: /order/{externalCode}/confirm-payment
  controller: App\Http\Controller\ConfirmOrderPaymentController::execute
  methods: [POST]

ship_order:
  path: /order/{externalCode}/ship
  controller: App\Http\Controller\ShipOrderController::execute
  methods: [POST]

create_order_invoice:
  path: /order/{externalCode}/invoice
  controller: App\Http\Controller\CreateOrderInvoiceController::execute
  methods: [POST]

mark_order_as_fraud:
  path: /order/{uuid}/mark-as-fraud
  controller: App\Http\Controller\MarkOrderAsFraudController::execute
  methods: [POST]

update_merchant_with_order_dunning_step:
  path: /order/{uuid}/update-dunning-step
  controller: App\Http\Controller\UpdateMerchantWithOrderDunningStepController::execute
  methods: [POST]

create_merchant:
  path: /merchant
  controller: App\Http\Controller\CreateMerchantController::execute
  methods: [POST]
