healthcheck:
  resource: '@BillieMonitoringBundle/Resources/config/routes.yaml'

public_health_check:
  path: /public/healthcheck
  controller:  Billie\MonitoringBundle\Controller\HealthCheckController::execute
  methods: [GET]

api_docs:
  resource: ../src/Http/Controller/ApiDocs
  type: openapi_annotation
  name_prefix: docs_

api_v1:
  resource: 'routes/public_api_v1.yaml'

api_v2:
  resource: 'routes/public_api_v2.yaml'

api_private:
  resource: 'routes/private_api.yaml'
