billie_monitoring:
  resource: '@BillieMonitoringBundle/Resources/config/routes.yaml'

public_api_controllers:
  resource: ../src/Http/Controller/PublicApi
  type: openapi_annotation

prefixed_public_api_controllers:
  resource: ../src/Http/Controller/PublicApi
  type: openapi_annotation
  prefix: /public
  name_prefix: public_

private_api_controllers:
  resource: ../src/Http/Controller/PrivateApi
  type: openapi_annotation
  prefix: /private
  name_prefix: private_

api_docs_controllers:
  resource: ../src/Http/Controller/ApiDocs
  type: openapi_annotation
