billie_monitoring:
  resource: '@BillieMonitoringBundle/Resources/config/routes.yaml'

controllers:
    resource: ../src/Http/Controller
    type: openapi_annotation

trigger_failed_order_notifications:
  path: /order/{id}/trigger-failed-notifications
  controller: App\Http\Controller\TriggerFailedOrderNotificationsController::execute
  methods: [POST]

mark_order_as_fraud:
  path: /order/{uuid}/mark-as-fraud
  controller: App\Http\Controller\MarkOrderAsFraudController::execute
  methods: [POST]

update_merchant_with_order_dunning_step:
  path: /order/{uuid}/update-dunning-step
  controller: App\Http\Controller\UpdateMerchantWithOrderDunningStepController::execute
  methods: [POST]

register_merchant_user:
  path: /merchant/{merchantId}/user
  controller: App\Http\Controller\RegisterMerchantUserController::execute
  methods: [POST]

update_merchant_debtor_limit:
  path: /merchant/{merchantId}/merchant-debtor/{merchantDebtorExternalId}/limit
  controller: App\Http\Controller\UpdateMerchantDebtorLimitController::execute
  methods: [PUT]

update_merchant_debtor_company:
  path: /merchant/{merchantId}/merchant-debtor/{merchantDebtorExternalId}/company
  controller: App\Http\Controller\UpdateMerchantDebtorCompanyController::execute
  methods: [PUT]

mark_duplicate_debtors:
  path: /merchant-debtor/mark-duplicates
  controller: App\Http\Controller\MarkDuplicateDebtorsController::execute
  methods: [POST]

whitelist_merchant_debtor:
  path: /merchant/{merchantId}/merchant-debtor/{merchantDebtorExternalId}/whitelist
  controller: App\Http\Controller\UpdateMerchantDebtorWhitelistController::execute
  methods: [PUT]

pause_order_dunning:
  path: /order/{id}/pause-dunning
  controller: App\Http\Controller\PauseOrderDunningController::execute
  methods: [POST]
