parameters:
  behat_mock_server_url: "http://localhost"
#  billie_monitoring_slack_webhook_url: ''

services:
  _defaults:
    autowire: true
    public: true

  App\Http\ApiError\ApiErrorResponseFactory: '@App\Http\ApiError\VerboseApiErrorResponseFactory'

  App\DomainModel\Order\OrderRepositoryInterface:
    alias: 'App\Infrastructure\Repository\OrderRepository'
    public: true
  App\DomainModel\Address\AddressRepositoryInterface:
    alias: 'App\Infrastructure\Repository\AddressRepository'
    public: true
  App\DomainModel\Person\PersonRepositoryInterface:
    alias: 'App\Infrastructure\Repository\PersonRepository'
    public: true
  App\DomainModel\DebtorExternalData\DebtorExternalDataRepositoryInterface:
    alias: 'App\Infrastructure\Repository\DebtorExternalDataRepository'
    public: true
  App\DomainModel\Merchant\MerchantRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantRepository'
    public: true
  App\DomainModel\MerchantDebtor\MerchantDebtorRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantDebtorRepository'
    public: true
  App\DomainModel\MerchantSettings\MerchantSettingsRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantSettingsRepository'
    public: true
  App\DomainModel\FraudRules\FraudRuleRepositoryInterface:
    alias: 'App\Infrastructure\Repository\FraudRuleRepository'
    public: true
  App\DomainModel\ScoreThresholdsConfiguration\ScoreThresholdsConfigurationRepositoryInterface:
    alias: 'App\Infrastructure\Repository\ScoreThresholdsConfigurationRepository'
    public: true
  App\DomainModel\OrderIdentification\OrderIdentificationRepositoryInterface:
    alias: 'App\Infrastructure\Repository\OrderIdentificationRepository'
    public: true
  App\DomainModel\MerchantRiskCheckSettings\MerchantRiskCheckSettingsRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantRiskCheckSettingsRepository'
    public: true
  App\DomainModel\OrderRiskCheck\RiskCheckDefinitionRepositoryInterface:
    alias: 'App\Infrastructure\Repository\RiskCheckDefinitionRepository'
    public: true
  App\DomainModel\OrderRiskCheck\OrderRiskCheckRepositoryInterface:
    alias: 'App\Infrastructure\Repository\OrderRiskCheckRepository'
    public: true
  App\DomainModel\MerchantUser\MerchantUserRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantUserRepository'
    public: true
  App\DomainModel\MerchantUser\MerchantUserRoleRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantUserRoleRepository'
    public: true
  App\DomainModel\MerchantUserInvitation\MerchantUserInvitationRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantUserInvitationRepository'
    public: true
  App\DomainModel\MerchantUserInvitation\MerchantUserInvitationEntityFactory:
    public: true
  App\DomainModel\CheckoutSession\CheckoutSessionRepositoryInterface:
    alias: 'App\Infrastructure\Repository\CheckoutSessionRepository'
    public: true
  App\DomainModel\Merchant\MerchantDebtorFinancialDetailsRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantDebtorFinancialDetailsRepository'
    public: true
  App\DomainModel\OrderFinancialDetails\OrderFinancialDetailsRepositoryInterface:
    alias: 'App\Infrastructure\Repository\OrderFinancialDetailsRepository'
    public: true
  App\DomainModel\MerchantNotificationSettings\MerchantNotificationSettingsRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantNotificationSettingsRepository'
    public: true
  App\DomainModel\OrderNotification\OrderNotificationRepositoryInterface:
    alias: 'App\Infrastructure\Repository\OrderNotificationRepository'
    public: true
  App\DomainModel\Payment\PaymentsRepositoryInterface:
    alias: 'App\DomainModel\Payment\EmptyPaymentsRepository'
    public: true
  App\DomainModel\MerchantOnboarding\MerchantOnboardingRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantOnboarding\MerchantOnboardingRepository'
    public: true
  App\DomainModel\MerchantOnboarding\MerchantOnboardingStepRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantOnboarding\MerchantOnboardingStepRepository'
    public: true
  App\DomainModel\MerchantOnboarding\MerchantOnboardingTransitionRepositoryInterface:
    alias: 'App\Infrastructure\Repository\MerchantOnboarding\MerchantOnboardingTransitionRepository'
    public: true
  App\DomainModel\MerchantOnboarding\MerchantOnboardingPersistenceService:
    public: true
  App\DomainModel\SignatoryPowersSelection\SignatoryPowerAutoIdentifyUserService:
    public: true
