parameters:
  locale: 'en'
  google_cloud_project_id: bbox-150315
  google_cloud_credentials_file_path: '%kernel.root_dir%/../config/secrets/gcloud.json'
  log_channel: paella_core

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    App\Infrastructure\Repository\AbstractRepository:
      tags: ['paella_core.repository']

    App\DomainModel\Monitoring\LoggingInterface:
      tags: ['paella_core.logging']

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Http\Controller\:
    resource: '../src/Http/Controller'
    tags: ['controller.service_arguments']

  paella_core.pdo:
    class: \PDO
    arguments:
      - 'mysql:dbname=%env(DATABASE_NAME)%;host=%env(DATABASE_HOST)%'
      - '%env(DATABASE_USERNAME)%'
      - '%env(DATABASE_PASSWORD)%'

  App\Infrastructure\Risky\Risky:
    arguments:
      $client: '@eight_points_guzzle.client.risky'

  App\Infrastructure\Alfred\Alfred:
    arguments:
      $client: '@eight_points_guzzle.client.alfred'

  App\Infrastructure\Borscht\Borscht:
    arguments:
      $client: '@eight_points_guzzle.client.borscht'

  App\DomainModel\Order\OrderRepositoryInterface: '@App\Infrastructure\Repository\OrderRepository'
  App\DomainModel\Address\AddressRepositoryInterface: '@App\Infrastructure\Repository\AddressRepository'
  App\DomainModel\Person\PersonRepositoryInterface: '@App\Infrastructure\Repository\PersonRepository'
  App\DomainModel\DebtorExternalData\DebtorExternalDataInterface: '@App\Infrastructure\Repository\DebtorExternalData'
  App\DomainModel\Customer\CustomerRepositoryInterface: '@App\Infrastructure\Repository\CustomerRepository'
  App\DomainModel\Customer\CompanyRepositoryInterface: '@App\Infrastructure\Repository\CompanyRepository'
  App\DomainModel\Customer\RiskCheckRepositoryInterface: '@App\Infrastructure\Repository\RiskCheckRepository'
  App\DomainModel\Company\CompanyRepositoryInterface: '@App\Infrastructure\Repository\CompanyRepository'
  App\DomainModel\OrderTransition\OrderTransitionRepositoryInterface: '@App\Infrastructure\Repository\OrderTransitionRepository'

  App\DomainModel\Alfred\AlfredInterface: '@App\Infrastructure\Alfred\Alfred'
  App\DomainModel\Borscht\BorschtInterface: '@App\Infrastructure\Borscht\Borscht'
  App\DomainModel\Risky\RiskyInterface: '@App\Infrastructure\Risky\Risky'

  App\Infrastructure\Monitoring\StackdriverLogHandler:
    arguments:
      $loggingClient: !service
        class: Google\Cloud\Logging\LoggingClient
        arguments:
          -
            projectId: '%google_cloud_project_id%'
            keyFilePath: '%google_cloud_credentials_file_path%'
      $env: '%env(INSTANCE_SUFFIX)%'
      $channel: '%log_channel%'

  Symfony\Component\Workflow\Workflow: '@state_machine.order'
