parameters:
  env(X_TEST_ID): ~
  x_test_id: '%env(string:X_TEST_ID)%'
#  billie_monitoring_slack_webhook_url: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Test\TestGuzzleSubscriber:
    arguments:
      $mockServerUrl: '%env(MOCKSERVER_URL)%'
      $servicesToMock: [salesforce]
      $servicesToProxyHeader: [alfred]
      $cliTestId: '%x_test_id%'
