parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    App\Infrastructure\AbstractRepository:
      tags: ['paella_core.repository']

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Http\Controller\:
    resource: '../src/Http/Controller'
    tags: ['controller.service_arguments']

  paella_core.pdo:
    class: \PDO
    arguments:
      - 'mysql:dbname=%env(DATABASE_NAME)%;host=%env(DATABASE_HOST)%'
      - '%env(DATABASE_USERNAME)%'
      - '%env(DATABASE_PASSWORD)%'

  App\DomainModel\Order\OrderRepositoryInterface: '@App\Infrastructure\OrderRepository'
  App\DomainModel\Customer\CustomerRepositoryInterface: '@App\Infrastructure\CustomerRepository'
